#!/usr/bin/perl
use strict;
use warnings;
use feature 'say';
sub Test {
  while ( my($index, $value) = each @_ ) {
    say "\$_[$index]:$value";
  }

}

&Test(1, 2, 3, 4, 5);
say @_[1];                       # 執行結束即消滅
